export const BotEquipSlot = {
    MAINHAND:    0,
    OFFHAND:     1,
    RANGED:      2,
    HEAD:        3,
    SHOULDERS:   4,
    CHEST:       5,
    WAIST:       6,
    LEGS:        7,
    FEET:        8,
    WRIST:       9,
    HANDS:      10,
    BACK:       11,
    BODY:       12, 
    FINGER1:    13,
    FINGER2:    14,
    TRINKET1:   15,
    TRINKET2:   16,
    NECK:       17,
  } as const;

export const BotSlotName = {
    0: "MAINHAND",
    1: "OFFHAND",
    2: "RANGED",
    3: "HEAD",
    4: "SHOULDER",
    5: "CHEST",
    6: "WAIST",
    7: "LEGS",
    8: "FEET",
    9: "WRIST",
    10: "HANDS",
    11: "BACK",
    12: "BODY",
    13: "FINGER1",
    14: "FINGER2",
    15: "TRINKET1",
    16: "TRINKET2",
    17: "NECK",
} as const;

export const BotEquipLast = 17;
    
export const BotStat = {
    MANA:                      0,
    HEALTH:                    1,
    AGILITY:                   3,
    STRENGTH:                  4,
    INTELLECT:                 5,
    SPIRIT:                    6,
    STAMINA:                   7,
    DEFENSE_SKILL_RATING:     12,
    DODGE_RATING:             13,
    PARRY_RATING:             14,
    BLOCK_RATING:             15,
    HIT_MELEE_RATING:         16,
    HIT_RANGED_RATING:        17,
    HIT_SPELL_RATING:         18,
    CRIT_MELEE_RATING:        19,
    CRIT_RANGED_RATING:       20,
    CRIT_SPELL_RATING:        21,
    HIT_TAKEN_MELEE_RATING:   22,
    HIT_TAKEN_RANGED_RATING:  23,
    HIT_TAKEN_SPELL_RATING:   24,
    CRIT_TAKEN_MELEE_RATING:  25,
    CRIT_TAKEN_RANGED_RATING: 26,
    CRIT_TAKEN_SPELL_RATING:  27,
    HASTE_MELEE_RATING:       28,
    HASTE_RANGED_RATING:      29,
    HASTE_SPELL_RATING:       30,
    HIT_RATING:               31,
    CRIT_RATING:              32,
    HIT_TAKEN_RATING:         33,
    CRIT_TAKEN_RATING:        34,
    RESILIENCE_RATING:        35,
    HASTE_RATING:             36,
    EXPERTISE_RATING:         37,
    ATTACK_POWER:             38,
    RANGED_ATTACK_POWER:      39,
    FERAL_ATTACK_POWER:       40,
    SPELL_HEALING_DONE:       41,
    SPELL_DAMAGE_DONE:        42,
    MANA_REGENERATION:        43,
    ARMOR_PENETRATION_RATING: 44,
    SPELL_POWER:              45,
    HEALTH_REGEN:             46,
    SPELL_PENETRATION:        47,
    BLOCK_VALUE:              48,   
    DAMAGE_MIN:               49,
    DAMAGE_MAX:               50,
    ARMOR:                    51,
    RESIST_HOLY:              52,
    RESIST_FIRE:              53,   
    RESIST_NATURE:            54,
    RESIST_FROST:             55,
    RESIST_SHADOW:            56,
    RESIST_ARCANE:            57,
    EXPERTISE:                58,
    MAX_BOT_ITEM_MOD:         59,
    BOT_STAT_MOD_RESISTANCE_START: 51, // Assuming BOT_STAT_MOD_ARMOR is defined somewhere
  } as const;
  
  export const BotStatLast = 58;
  
export const UIInvSlot = {
    AMMOSLOT: "AMMOSLOT",
    HEADSLOT: "HEADSLOT",
    NECKSLOT: "NECKSLOT",
    SHOULDERSLOT: "SHOULDERSLOT",
    SHIRTSLOT: "SHIRTSLOT",
    CHESTSLOT: "CHESTSLOT",
    WAISTSLOT: "WAISTSLOT",
    LEGSSLOT: "LEGSSLOT",
    FEETSLOT: "FEETSLOT",
    WRISTSLOT: "WRISTSLOT",
    HANDSSLOT: "HANDSSLOT",
    FINGER0SLOT: "FINGER0SLOT",
    FINGER1SLOT: "FINGER1SLOT",
    TRINKET0SLOT: "TRINKET0SLOT",
    TRINKET1SLOT: "TRINKET1SLOT",
    BACKSLOT: "BACKSLOT",
    MAINHANDSLOT: "MAINHANDSLOT",
    SECONDARYHANDSLOT: "SECONDARYHANDSLOT",
    RANGEDSLOT: "RANGEDSLOT",
    TABARDSLOT: "TABARDSLOT",
  } as const;

  export const ClassesMapping: Record<number, string> = {
    1: "Warrior",
    2: "Paladin",
    3: "Hunter",
    4: "Rogue",
    5: "Priest",
    6: "Death Knight",
    7: "Shaman",
    8: "Mage",
    9: "Warlock",
    10: "Druid",
    11: "Blade Master",
    12: "Sphynx",
    13: "Archmage",
    14: "Dreadlord",
    15: "Spellbreaker",
    16: "Dark Ranger",
    17: "Necromancer",
    18: "Sea Witch",
    19: "Crypt Lord",
  } as const;

export type CharacterClass = typeof ClassesMapping[keyof typeof ClassesMapping];

export const RacesMapping: Record<number, string> = {
    1: "Human",
    2: "Orc",
    3: "Dwarf",
    4: "Night Elf",
    5: "Undead",
    6: "Tauren",
    7: "Gnome",
    8: "Troll",
    9: "Goblin",
    10: "Blood Elf",
    11: "Draenei",
    12: "Worgen",
} as const;

export type CharacterRace = typeof RacesMapping[keyof typeof RacesMapping];